default: &default
  # Database configuration
  DB_PORT: "5432"
  DB_POOL: <%= ENV.fetch("RAILS_MAX_THREADS") { "5" } %>
  DB_HOST: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  # Mailer configuration
  SMTP_ADDRESS: "smtp email address"
  SMTP_DOMAIN: "smtp email domain"
  SMTP_PORT: "587"
  SMTP_USERNAME: "smtp email username"
  SMTP_PASSWORD: "smtp email password"
  # GeoCoder configuration (developer.here.com)
  GEOCODER_LOOKUP_APP_ID: "here_app_id"
  GEOCODER_LOOKUP_APP_CODE: "here_app_code"

development:
  <<: *default
  DATABASE_DATABASE: "participa_catalunya_development"
  DATABASE_USERNAME: <%= ENV.fetch("DATABASE_USERNAME") { "" } %>
  DATABASE_PASSWORD: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>

test:
  <<: *default
  TEST_DB_DATABASE: "participa_catalunya_test"
  TEST_DB_USERNAME: "admin"
  TEST_DB_PASSWORD: "admin"

integration:
  <<: *default
  # secrets
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>

staging:
  <<: *default

production:
  <<: *default
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>
